### ISSUE TITLE
Huge memory usage with checkrepos

### ISSUE THREAD

**Issue by Rocco83** [RedHatSatellite/katello-cvmanager#20]
In case of --checkrepos may get to very high memory size can grow indefinitely.

USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root     11874 33.3 18.3 6247752 6024124 pts/11 Sl+ 18:18  33:05 ruby ./cvmanager --wait --checkrepos --config=cvmanager-xxx.yaml publish

At a brief look seems to me that https://github.com/RedHatSatellite/katello-cvmanager/blob/master/cvmanager#L334 is the problem.
What happens is that alll of tasks are extracted, and 

Probably also https://bugzilla.redhat.com/show_bug.cgi?id=1362168#c20 can be part of the cause.

@cliles involving you as main contributor, i will give a try fixing the code.
PR should came shortly.

**Comment by cliles** [comment]
@Rocco83  - yes, what happens is that we end up pulling every Actions::Katello::Repository::Sync task if the last_sync contains no new packages. This is to check for additional syncs that could have been triggered between the last cvmanager run.

What to do?

Yes the api hit to pull all Actions::Katello::Repository::Sync is not optimized, and horrible in that we are stuffing every task into an array to then just ignore them later. I'll give it a go at optimizing, but the instance I am developing against does not have many tasks.
