### ISSUE TITLE
log output when skipping CVs for some reason

### ISSUE THREAD

**Issue by evgeni** [RedHatSatellite/katello-cvmanager#22]
we skip stuff based on rules, but the user never sees that decision
identified in #18

**Comment by Rocco83** [comment]
in which functions?
publish, promote, update, clean?
Again, something done in https://github.com/RedHatSatellite/katello-cvmanager/pull/24

**Comment by evgeni** [comment]
closed via 44d807503128cdf36ecfc5708304515c46c16d42
