### ISSUE TITLE
decide whether to use labels or names when looking for CVs

### ISSUE THREAD

**Issue by evgeni** [RedHatSatellite/katello-cvmanager#23]
we currently use names, those might change. labels are better. also add docs saying so.

identified in #18

**Comment by Rocco83** [comment]
As the title is "decide whether", +1 on labels.
Documentation has to say that also that labels should be the same as names and space should not be used in names, btw :)

**Comment by bergsjoh** [comment]
Why not check both, if name fails check label.

**Comment by evgeni** [comment]
IIRC names don't have to be unique. So I'd rather not do them in the long term.

**Comment by alosadagrande** [comment]
Names on CV are unique otherwise an error is thrown while saving

**Comment by evgeni** [comment]
fixed in b997a78
