### ISSUE TITLE
Publish not possible if local repository is inside CV

### ISSUE THREAD

**Issue by kawatyp** [RedHatSatellite/katello-cvmanager#28]
Our base OS RHEL7 CV consists of several RedHat repos and also of one repo for thirdparty content.
The one repo from our thirdparty product is a local filerepo with only one RPM inside.
When trying to publish a new of the base OS CV cvmanager checks for new Versions and then breaks with:

./cvmanager:353:in `block (2 levels) in publish': undefined method `has_key?' for nil:NilClass (NoMethodError)
        from ./cvmanager:349:in `each'
        from ./cvmanager:349:in `block in publish'
        from ./cvmanager:325:in `each'
        from ./cvmanager:325:in `publish'
        from ./cvmanager:476:in `<main>'
When i remove the one local repo publishing works like expected.
I suppose it breaks because the sync state and date of the local repo is always set and displayed as N/A.
Is there any way to skip the check for new versions so that this missing sync state/date is ignored ?

**Comment by evgeni** [comment]
closed via https://github.com/RedHatSatellite/katello-cvmanager/commit/a87df290c2413c23fe19dcaf5e4d570ea1fcecfb
