### ISSUE TITLE
Could not load data from https://localhost

### ISSUE THREAD

**Issue by PSP2017** [RedHatSatellite/katello-cvmanager#49]
Hi, 
while trying publish a content view, I have the following message:
------------------------------------------------------------------------------------------------------------
# ./cvmanager --wait publish
/usr/share/gems/gems/apipie-bindings-0.0.14/lib/apipie_bindings/api.rb:268:in `rescue in retrieve_apidoc': Could not load data from https://localhost (ApipieBindings::DocLoadingError)

    is your server down?
    was rake apipie:cache run when using apipie cache? (typical production settings)
    from /usr/share/gems/gems/apipie-bindings-0.0.14/lib/apipie_bindings/api.rb:265:in retrieve_apidoc' from /usr/share/gems/gems/apipie-bindings-0.0.14/lib/apipie_bindings/api.rb:115:inapidoc'
    from /usr/share/gems/gems/apipie-bindings-0.0.14/lib/apipie_bindings/resource.rb:8:in initialize' from /usr/share/gems/gems/apipie-bindings-0.0.14/lib/apipie_bindings/api.rb:128:innew'
    from /usr/share/gems/gems/apipie-bindings-0.0.14/lib/apipie_bindings/api.rb:128:in resource' from ./cvmanager:351:inpublish'
    from ./cvmanager:517:in `'
----------------------------------------------------------------------------------------------------------------
Can someone help me ?
# cat cvmanager.yaml
---
:settings:
  :user: admin
  :pass:XXXXX
  :uri: https://localhost
  :timeout: 300
  :org: 1
  :lifecycle: 2
  :keep: 10
:ccv:
  CCV_RHEL7_RHSC7_OPT7:
    CV_OPT7: latest
    CV_RHEL7: latest
    CV_RHSC7: latest
:publish:
  - CV_OPT7
  - CV_RHEL7
  - CV_RHSC7

:promote:
  - CCV_RHEL7_RHSC7_OPT7

**Comment by fm0l** [comment]
Is your Satellite server published at https://localhost? You should use the same FQDN you use to connect to it, use API, smart proxy ecc..
Being in HTTPS and requiring a certificate you should use the same name you configured during installation

**Comment by PSP2017** [comment]
it works with FQDN, thanks
