### ISSUE TITLE
cvmanager needs to be updated to work with Satellite version 6.3.x

### ISSUE THREAD

**Issue by gearboxscott** [RedHatSatellite/katello-cvmanager#51]
Update to README.md to inform that apipie needs to be installed with gem install.

Update composite content view update to allow for "latest" when checking for publishing a new version of the composite content view.

**Comment by peppos** [comment]
Hi, this is the rpm list apipie to work with Satellite 6.3 
    Install     rubygem-apipie-bindings-0.0.8-1.el7sat.noarch @rhel-7-server-rh-common-rpms
    Dep-Install rubygem-awesome_print-1.0.2-12.el7sat.noarch  @rhel-7-server-rh-common-rpms
    Dep-Install rubygem-fastercsv-1.5.4-10.el7sat.noarch      @rhel-7-server-rh-common-rpms
    Dep-Install rubygem-oauth-0.5.1-1.el7sat.noarch           @rhel-7-server-satellite-6.3-rpms

**Comment by gearboxscott** [comment]
it worked before without all this stuff.  

the issue is the 6.3.1 sets the options for composite content views to "latest" so you don't have edit the CCV to change version, you can just publish it.   

So far, none of the changes in the code since entering this issue has fixed the issue. 

This has nothing to do with missing apipie because you can just easily change to tfm-ruby and it runs.

**Comment by gearboxscott** [comment]
I'm going to pursue a script with hammer command in it.
