### ISSUE TITLE
cannot load such file -- apipie-bindings

### ISSUE THREAD

**Issue by abradshaw** [RedHatSatellite/katello-cvmanager#63]
Fresh install of cvmanager on 6.4.1

- Did the git clone
- Updated the username/password/uri
- tried to run 

```
[root@sat6 katello-cvmanager]# ./cvmanager clean
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- apipie-bindings (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./cvmanager:20:in `<main>'
```

**Comment by jgkootstra** [comment]
cvmanager breaks with error like @abradshaw.
Got it after an update from RH Satellite 6.4.3 to RH Satellite 6.5.0

**Comment by pcfe** [comment]
like @jgkootstra I get the error after upgrading from 6.4 to 6.5
under 6.4 (originally installed as 6.2,m upgraded during it's life) I would *not* get the error

**Comment by abradshaw** [comment]
this seems to work

 `# tfm-ruby ./cvmanager clean
`

**Comment by evgeni** [comment]
Yeah, Satellite does not ship with `apipie-bindings` for the non-SCL Ruby. Use either `tfm-ruby` or install `apipie-bindings` yourself.
