### ISSUE TITLE
Consider adding repository syncing

### ISSUE THREAD

**Issue by OrangeCrush** [RedHatSatellite/katello-cvmanager#7]
I think it'd also be useful to also add an option to sync repositories in satellite before promoting or publishing content views.  Let me know if you think this functionality is a good candidate for this piece of software.

This is something I would be interested in working on in the near future.

**Comment by evgeni** [comment]
Hi @OrangeCrush,

do you mean literally run a sync job to copy stuff from CDN to Katello? Like you can do in the UI and via a Sync Plan?

Yeah, why not. Would you provide a patch?
We use Sync Plans, so this functionality is not needed for us at the moment, but I'd definitely merge it if its useful for others.

**Comment by OrangeCrush** [comment]
I think you're correct that sync plans handle this functionality fine.  At least this issue gave me an opportunity to thank everyone for working on this piece of software!  It works without any kinks.  Thanks
